### ISSUE TITLE
Allows for beyond vanilla levels of Sprint speed

### ISSUE THREAD

**Issue by Mattabase** [AvacadoWizard120/Omni#1]
If you are already sprinting forward and you hit the sprint key again, you run faster than vanilla sprint speeds allow.

(on further testing I have not confirmed if the new speed is faster, it just may be that your sprinting itself is faster)

**Comment by AvacadoWizard120** [comment]
Okay so I it is faster than vanilla sprint when you are going forward. You can still vanilla sprint by double tapping your forward key, but as soon as you press the sprint key is when the movement takes effect. I'm not going to change the speed, but I'm going ahead and adding a config where you can modify the speed multipliers of sprinting left, right, forwards, and backwards. 

This mod is fully client-sided which means if you want to run it on a server, you don't have to have it on the server itself, unless you don't want people getting kicked for cheating. I accidentally went on CubeCraft with the mod and forgot I had Omni on my profile (after testing I forgot to delete) and the mod itself was working in CubeCraft undetected which I thought was wild; it works insanely well in PvP btw you can just sprint around people and just be hitting them constantly...
